services:
  - type: web
    name: rapid-recap
    env: docker
    plan: free
    branch: RRConceptRemdeling
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: PUBLIC_VAPID_KEY
        sync: false
      - key: PRIVATE_VAPID_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REFRESH_TOKEN
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
