const bios = [
  "Lifelong learner, always seeking new knowledge and experiences. Enthusiast of art, literature, and philosophy. Believer in the power of curiosity to drive personal growth.",
  "Tech enthusiast and aspiring coder. Passionate about creating innovative solutions to real-world problems. Constantly exploring the latest trends in technology.",
  "Adventurous soul with a love for the great outdoors. Hiking, camping, and mountain biking are my go-to activities. Nature lover and advocate for environmental conservation.",
  "Animal lover and volunteer at the local shelter. Advocate for pet adoption and animal rights. Proud owner of two rescue dogs and a cat.",
  "Foodie and amateur chef, always experimenting with new recipes and cuisines. Lover of good food, good wine, and great company. Firm believer that life is too short to eat boring food.",
  "Music enthusiast with a passion for playing the guitar. From blues to rock, I love exploring different genres and creating my own music. Believer in the therapeutic power of melodies.",
  "Fitness fanatic and personal trainer, dedicated to helping others achieve their health and wellness goals. Firm believer in the mind-body connection and the importance of self-care.",
  "Art lover and aspiring artist. Painting, sketching, and photography are my creative outlets. Inspired by nature, emotions, and the beauty of everyday life.",
  "Travel addict always planning the next adventure. From backpacking across Europe to road trips through the countryside, I thrive on new experiences and cultural immersion.",
  "Bookworm and literature enthusiast. Lost in the pages of a good book, transported to different worlds and time periods. Firm believer that words have the power to change lives.",
  "Film buff and aspiring filmmaker. From classic cinema to indie gems, I love exploring the art of storytelling through film. Always on the lookout for the next cinematic masterpiece.",
  "Fashion enthusiast with an eye for style. From streetwear to haute couture, I love experimenting with different looks and trends. Firm believer that fashion is a form of self-expression.",
  "Environmental activist and advocate for sustainability. Passionate about reducing waste, promoting eco-friendly practices, and protecting the planet for future generations.",
  "Coffee aficionado and self-proclaimed caffeine addict. From espresso to pour-over, I appreciate the art and science of brewing the perfect cup. Firm believer that coffee makes everything better.",
  "Gamer and esports enthusiast. From competitive gaming to casual play, I love immersing myself in virtual worlds and digital adventures. Firm believer that gaming is more than just a hobby—it's a lifestyle.",
  "Science nerd and astronomy enthusiast. From stargazing to astrophotography, I love exploring the wonders of the cosmos. Firm believer that the universe holds endless possibilities.",
  "Entrepreneur with a passion for innovation. From startups to corporate ventures, I thrive on turning ideas into reality. Firm believer that entrepreneurship is the key to driving positive change.",
  "History buff and amateur historian. From ancient civilizations to modern revolutions, I love exploring the past and uncovering the stories of those who came before us. Firm believer that understanding history is essential to shaping the future.",
  "Yoga practitioner and mindfulness coach. Dedicated to helping others find balance, peace, and inner harmony. Firm believer that yoga is a journey of self-discovery and transformation.",
  "Outdoor enthusiast and weekend warrior. From rock climbing to kayaking, I love pushing my limits and exploring the natural world. Firm believer that adventure awaits just beyond the beaten path.",
  "Artificial intelligence researcher and futurist. From machine learning to neural networks, I'm passionate about exploring the frontiers of AI and its potential to revolutionize society. Firm believer that the future is what we make it.",
  "Language lover and polyglot. From Spanish to Mandarin, I'm always learning new languages and exploring different cultures. Firm believer that language is the key to understanding and connecting with others.",
  "Mental health advocate and mindfulness practitioner. Dedicated to breaking the stigma surrounding mental illness and promoting holistic wellness. Firm believer that self-care is the foundation of a happy and fulfilling life.",
  "Surfing enthusiast and beach bum. From dawn patrols to sunset sessions, I love riding the waves and soaking up the sun. Firm believer that life's better when you're salty and sandy.",
  "Photography enthusiast with an eye for beauty. From landscapes to portraits, I love capturing moments and telling stories through the lens. Firm believer that every picture tells a thousand words.",
  "Music producer and DJ. From beats to basslines, I love creating infectious grooves and getting the crowd moving. Firm believer that music has the power to unite and uplift.",
  "Gardening guru and plant parent. From succulents to orchids, I love cultivating green spaces and bringing nature indoors. Firm believer that a little greenery can brighten any space.",
  "Political junkie and activist. From canvassing to campaigning, I'm dedicated to making a difference and fighting for social justice. Firm believer that change starts with a single voice.",
  "Equestrian enthusiast and horse whisperer. From dressage to show jumping, I love connecting with these majestic animals and experiencing the freedom of the open trail. Firm believer that horses have a special bond with humans.",
  "Astrology aficionado and cosmic explorer. From birth charts to horoscopes, I love delving into the mysteries of the zodiac and uncovering the secrets of the stars. Firm believer that the universe has a plan for us all.",
  "Vintage collector and thrift store aficionado. From vinyl records to retro fashion, I love hunting for hidden treasures and reliving the glory days of the past. Firm believer that everything old is new again.",
  "Sustainability advocate and zero waste warrior. From composting to upcycling, I'm dedicated to reducing my ecological footprint and living in harmony with the planet. Firm believer that small actions can lead to big changes.",
  "Entrepreneur and startup founder. From pitch decks to product launches, I'm passionate about building businesses that make a difference. Firm believer that innovation is the key to success in the modern world.",
  "Martial artist and self-defense instructor. From kung fu to jiu-jitsu, I love honing my skills and empowering others to protect themselves. Firm believer that strength comes from within.",
  "Adventure photographer and outdoor explorer. From mountain peaks to remote valleys, I love capturing the beauty of the natural world and inspiring others to explore it. Firm believer that life's greatest adventures are found off the beaten path.",
  "Fashion designer and style icon. From runway shows to fashion shoots, I love pushing the boundaries of creativity and expressing myself through clothing. Firm believer that fashion is art.",
  "Dog lover and rescue advocate. From fostering to volunteering, I'm dedicated to giving back to our furry friends and finding them loving homes. Firm believer that every dog deserves a chance.",
  "Travel blogger and digital nomad. From remote islands to bustling cities, I love sharing my adventures and inspiring others to see the world. Firm believer that travel is the best education.",
  "Film critic and cinema aficionado. From blockbusters to indie gems, I love dissecting films and uncovering the deeper meanings behind the stories. Firm believer that movies have the power to change lives.",
  "Coffee connoisseur and barista extraordinaire. From latte art to cold brews, I'm passionate about all things coffee and love sharing my knowledge with others. Firm believer that coffee is more than just a drink—it's a way of life.",
  "Environmental activist and climate warrior. From protests to policy advocacy, I'm dedicated to fighting for a sustainable future and preserving our planet for generations to come. Firm believer that together, we can make a difference.",
  "Photography enthusiast and visual storyteller. From street scenes to landscapes, I love capturing the beauty of everyday life and sharing it with the world. Firm believer that a picture is worth a thousand words.",
  "Music lover and vinyl collector. From classic rock to jazz, I'm always on the hunt for new records and hidden gems. Firm believer that music is the soundtrack to life.",
  "Fitness fanatic and personal trainer. From HIIT workouts to yoga sessions, I'm dedicated to helping others achieve their health and wellness goals. Firm believer that a strong body leads to a strong mind.",
  "Tech enthusiast and gadget geek. From smartphones to smart homes, I love exploring the latest tech trends and discovering new innovations. Firm believer that technology has the power to change the world.",
  "Art lover and gallery hopper. From contemporary art to street murals, I'm passionate about exploring the vibrant art scene and supporting local artists. Firm believer that art has the power to inspire and provoke.",
  "Nature lover and wildlife enthusiast. From birdwatching to camping, I love immersing myself in the great outdoors and connecting with the natural world. Firm believer that nature is our greatest teacher.",
  "Bookworm and literary aficionado. From classic novels to modern poetry, I'm always diving into new books and discovering hidden literary treasures. Firm believer that words have the power to transform lives.",
  "Film buff and cinephile. From cult classics to indie darlings, I love exploring the rich tapestry of cinema and uncovering the stories that shape our world. Firm believer that movies are more than just entertainment—they're a window into the human experience.",
  "Foodie and culinary explorer. From street food to fine dining, I'm always on the lookout for new flavors and culinary experiences. Firm believer that food is the universal language of love.",
  "Musician and songwriter. From guitar solos to heartfelt lyrics, I'm passionate about creating music that moves the soul and touches the heart. Firm believer that music has the power to heal.",
  "Adventure seeker and thrill chaser. From skydiving to bungee jumping, I'm always on the hunt for the next adrenaline rush. Firm believer that life begins at the end of your comfort zone.",
  "Gardening guru and plant whisperer. From succulents to roses, I love tending to my garden and watching it bloom. Firm believer that gardening is good for the soul.",
  "Political junkie and grassroots organizer. From door-knocking to phone-banking, I'm dedicated to making a difference in my community and beyond. Firm believer that activism is the key to progress.",
  "Eco-warrior and sustainability advocate. From recycling to upcycling, I'm committed to living a low-impact lifestyle and protecting the planet for future generations. Firm believer that every action counts.",
  "Entrepreneur and startup enthusiast. From brainstorming to business development, I'm passionate about turning ideas into reality and building successful ventures. Firm believer that innovation drives progress.",
  "Yoga practitioner and mindfulness coach. From downward dog to meditation, I'm dedicated to cultivating inner peace and harmony. Firm believer that yoga is the path to enlightenment.",
  "Outdoor enthusiast and nature lover. From hiking to camping, I'm always exploring the great outdoors and soaking up the beauty of Mother Nature. Firm believer that adventure is out there.",
  "Art lover and creative spirit. From painting to pottery, I'm passionate about expressing myself through art and exploring my imagination. Firm believer that creativity is the key to happiness.",
  "Animal lover and pet parent. From cats to dogs, I'm dedicated to providing love and care to all creatures great and small. Firm believer that pets make life better.",
  "Traveler and wanderlust enthusiast. From backpacking to luxury vacations, I'm always on the move and exploring new destinations. Firm believer that travel is the best education.",
  "Film buff and cinephile. From Hollywood blockbusters to indie gems, I'm passionate about all things cinema and love dissecting films. Firm believer that movies have the power to change the world.",
  "Coffee connoisseur and espresso enthusiast. From pour-overs to lattes, I'm passionate about all things coffee and love exploring new roasts. Firm believer that coffee is the nectar of the gods.",
  "Environmental activist and sustainability advocate. From beach cleanups to tree plantings, I'm dedicated to protecting our planet and fighting climate change. Firm believer that small actions can make a big difference.",
  "Photography enthusiast and visual storyteller. From street scenes to landscapes, I love capturing the beauty of the world around me and sharing it with others. Firm believer that a picture is worth a thousand words.",
  "Music lover and vinyl collector. From classic rock to jazz, I'm always on the hunt for new records and hidden gems. Firm believer that music is the universal language of the soul.",
  "Fitness fanatic and gym junkie. From weightlifting to yoga, I'm passionate about staying active and living a healthy lifestyle. Firm believer that a strong body leads to a strong mind.",
  "Tech enthusiast and gadget guru. From smartphones to smartwatches, I love exploring the latest tech trends and discovering new innovations. Firm believer that technology is the key to progress.",
  "Art lover and museum aficionado. From Renaissance masterpieces to contemporary installations, I'm passionate about exploring the rich tapestry of art history. Firm believer that art is the soul of civilization.",
  "Nature lover and outdoor enthusiast. From hiking to kayaking, I'm always exploring the great outdoors and soaking up the beauty of Mother Nature. Firm believer that adventure is out there.",
  "Bookworm and literary aficionado. From classic novels to modern poetry, I'm always diving into new books and discovering hidden literary treasures. Firm believer that reading is the ultimate escape.",
  "Film buff and cinema aficionado. From blockbusters to indie darlings, I love exploring the rich tapestry of cinematic history and uncovering hidden gems. Firm believer that movies are a window into the human soul.",
  "Foodie and culinary explorer. From street food to fine dining, I'm always on the hunt for new flavors and culinary experiences. Firm believer that food is the ultimate expression of culture.",
  "Musician and songwriter. From guitar solos to heartfelt lyrics, I'm passionate about creating music that moves the soul and touches the heart. Firm believer that music is the universal language of emotion.",
  "Adventure seeker and thrill chaser. From skydiving to rock climbing, I'm always on the hunt for the next adrenaline rush. Firm believer that life is an adventure best lived boldly.",
  "Gardening guru and plant whisperer. From roses to tomatoes, I love tending to my garden and watching it flourish. Firm believer that gardening is good for the soul.",
  "Political junkie and activist. From protests to petitions, I'm dedicated to making a difference in the world and fighting for social justice. Firm believer that every voice matters.",
  "Eco-warrior and sustainability advocate. From reducing waste to supporting renewable energy, I'm committed to living a green lifestyle and protecting the planet. Firm believer that we can create a brighter future together.",
  "Entrepreneur and startup founder. From ideation to execution, I'm passionate about building businesses that make a positive impact on the world. Firm believer that innovation is the key to progress.",
  "Yoga practitioner and mindfulness coach. From sun salutations to meditation, I'm dedicated to finding inner peace and balance. Firm believer that yoga is the path to enlightenment.",
  "Outdoor enthusiast and nature lover. From hiking to camping, I'm always exploring the great outdoors and soaking up the beauty of the natural world. Firm believer that adventure awaits around every corner.",
  "Art lover and creative soul. From painting to sculpting, I'm passionate about expressing myself through art and exploring my imagination. Firm believer that creativity is the spark of life.",
  "Animal lover and advocate. From shelter volunteering to wildlife conservation, I'm dedicated to protecting and caring for animals in need. Firm believer that every creature deserves love and respect.",
  "Traveler and explorer. From ancient ruins to modern cities, I'm always seeking new adventures and experiences. Firm believer that travel broadens the mind and enriches the soul.",
  "Film buff and cinephile. From classic Hollywood to international cinema, I'm passionate about all things film and love exploring the magic of storytelling on the silver screen. Firm believer that movies have the power to change lives.",
  "Coffee aficionado and barista extraordinaire. From espresso to pour-over, I'm passionate about all things coffee and love sharing my knowledge and passion with others. Firm believer that a good cup of coffee can brighten any day.",
  "Environmental advocate and sustainability champion. From recycling to activism, I'm dedicated to protecting the planet and creating a more sustainable future for generations to come. Firm believer that every action counts.",
  "Photography enthusiast and visual storyteller. From landscapes to portraits, I'm passionate about capturing moments and telling stories through the lens. Firm believer that a picture is worth a thousand words.",
  "Music lover and vinyl collector. From rock to jazz, I'm always on the hunt for new records and hidden gems. Firm believer that music is the soundtrack to life.",
  "Fitness fanatic and gym enthusiast. From weightlifting to yoga, I'm passionate about staying active and living a healthy lifestyle. Firm believer that exercise is the key to physical and mental well-being.",
  "Tech enthusiast and gadget geek. From smartphones to smart homes, I'm fascinated by the latest tech trends and innovations. Firm believer that technology has the power to change the world for the better.",
  "Art lover and museum aficionado. From Renaissance paintings to modern installations, I'm passionate about exploring the rich tapestry of art history and culture. Firm believer that art is a reflection of society.",
  "Nature lover and outdoor enthusiast. From hiking to kayaking, I'm happiest when I'm exploring the great outdoors and connecting with the beauty of the natural world. Firm believer that adventure is out there waiting to be discovered.",
  "Bookworm and literary aficionado. From classic novels to contemporary fiction, I'm always diving into new books and exploring different genres. Firm believer that reading is the ultimate escape.",
  "Film buff and cinephile. From Hollywood blockbusters to indie darlings, I'm passionate about all things film and love immersing myself in cinematic storytelling. Firm believer that movies have the power to inspire and entertain.",
  "Foodie and culinary enthusiast. From fine dining to street food, I'm always on the lookout for new flavors and culinary experiences. Firm believer that food is a universal language that brings people together.",
  "Musician and songwriter. From guitar riffs to lyrical melodies, I'm passionate about creating music that resonates with the soul. Firm believer that music has the power to heal and inspire.",
  "Adventure seeker and outdoor explorer. From mountain peaks to hidden trails, I'm always seeking new adventures and experiences in the great outdoors. Firm believer that life is an adventure best lived boldly.",
  "Gardening enthusiast and plant lover. From flower beds to vegetable patches, I'm passionate about cultivating green spaces and connecting with nature. Firm believer that gardening is good for the mind, body, and soul.",
  "Political activist and advocate. From rallies to petitions, I'm dedicated to fighting for social justice and equality for all. Firm believer that activism is the key to positive change.",
  "Environmental advocate and eco-warrior. From beach cleanups to tree plantings, I'm committed to protecting the planet and creating a more sustainable future for generations to come. Firm believer that every action counts.",
  "Entrepreneur and startup enthusiast. From idea conception to business launch, I'm passionate about building innovative ventures that make a positive impact on the world. Firm believer that entrepreneurship is the engine of progress.",
  "Yoga practitioner and mindfulness coach. From sun salutations to meditation, I'm dedicated to finding inner peace and balance in a chaotic world. Firm believer that yoga is the path to holistic wellness.",
  "Outdoor enthusiast and nature lover. From hiking trails to camping sites, I'm happiest when I'm surrounded by the beauty of the natural world. Firm believer that adventure is out there, waiting to be discovered.",
  "Art lover and creative soul. From paintbrushes to sketchpads, I'm passionate about expressing myself through art and exploring my creativity. Firm believer that art has the power to inspire and transform.",
  "Animal lover and pet parent. From dogs to cats, I'm dedicated to providing love and care to furry friends in need. Firm believer that pets enrich our lives and bring joy to our hearts.",
  "Traveler and explorer. From ancient ruins to modern cities, I'm always seeking new adventures and experiences around the globe. Firm believer that travel broadens the mind and feeds the soul.",
];

module.exports = bios;
