// Common terms organized by news categories
const commonTermsByCategory = {
  // Business & Economy
  business: [
    'investment',
    'corporate',
    'financial',
    'economic',
    'commercial',
    'industrial',
    'operations',
    'regulatory',
    'manufacturing',
    'enterprise',
    'organizational',
    'revenue',
    'monetary',
    'inflation',
    'consumption',
    'productivity',
    'partnership',
    'stakeholder',
    'infrastructure',
    'competitive',
    'strategic',
    'profitable',
    'subsidiary',
    'acquisition',
    'institutional',
  ],

  // Politics & Government
  politics: [
    'government',
    'political',
    'parliamentary',
    'democratic',
    'constitutional',
    'administrative',
    'legislative',
    'representative',
    'diplomatic',
    'ministerial',
    'opposition',
    'electoral',
    'presidential',
    'bureaucratic',
    'governance',
    'officials',
    'authority',
    'judiciary',
    'federation',
    'democracy',
  ],

  // Technology
  technology: [
    'technology',
    'digital',
    'innovation',
    'electronic',
    'application',
    'automated',
    'computational',
    'programming',
    'infrastructure',
    'artificial',
    'operational',
    'functionality',
    'interactive',
    'connectivity',
    'technological',
    'algorithm',
    'processing',
    'automation',
    'implementation',
    'integration',
  ],

  // Health & Medicine
  health: [
    'medical',
    'nutritional',
    'pharmaceutical',
    'therapeutic',
    'prevention',
    'treatment',
    'diagnostic',
    'beneficial',
    'immunity',
    'inflammatory',
    'medication',
    'supplementary',
    'respiratory',
    'vaccination',
    'prescription',
    'traditional',
    'professional',
    'alternative',
    'digestive',
    'psychological',
  ],

  // Science
  science: [
    'scientific',
    'experimental',
    'analytical',
    'theoretical',
    'mathematical',
    'statistical',
    'biological',
    'chemical',
    'physical',
    'environmental',
    'molecular',
    'geological',
    'astronomical',
    'evolutionary',
    'computational',
    'laboratory',
    'systematic',
    'methodical',
    'observation',
    'hypothesis',
  ],

  // Sports
  sports: [
    'competitive',
    'professional',
    'championship',
    'performance',
    'tournament',
    'recreational',
    'international',
    'traditional',
    'consecutive',
    'qualification',
    'exceptional',
    'celebration',
    'individual',
    'statistical',
    'competition',
    'achievement',
    'dedication',
    'prestigious',
    'recognition',
    'extraordinary',
  ],

  // Entertainment
  entertainment: [
    'entertainment',
    'performance',
    'celebration',
    'production',
    'theatrical',
    'contemporary',
    'traditional',
    'spectacular',
    'presentation',
    'promotional',
    'television',
    'celebrated',
    'popularity',
    'prestigious',
    'personality',
    'remarkable',
    'exceptional',
    'fascinating',
    'memorable',
    'extraordinary',
  ],

  // Environment
  environment: [
    'environmental',
    'sustainable',
    'conservation',
    'ecological',
    'agricultural',
    'biodiversity',
    'preservation',
    'responsibility',
    'atmospheric',
    'renewable',
    'pollination',
    'contamination',
    'deforestation',
    'sustainability',
    'biological',
    'initiative',
    'protection',
    'ecosystem',
    'adaptation',
    'mitigation',
  ],

  // Education
  education: [
    'educational',
    'academic',
    'institutional',
    'professional',
    'intellectual',
    'curriculum',
    'developmental',
    'understanding',
    'examination',
    'qualification',
    'achievement',
    'performance',
    'assessment',
    'evaluation',
    'certification',
    'opportunity',
    'practical',
    'theoretical',
    'elementary',
    'university',
  ],

  // General/Common
  general: [
    'approximately',
    'significantly',
    'particularly',
    'considerable',
    'improvement',
    'development',
    'organization',
    'establishment',
    'information',
    'communication',
    'appreciation',
    'relationship',
    'opportunity',
    'traditional',
    'immediately',
    'appropriate',
    'understand',
    'experience',
    'reasonable',
    'community',
    'absolutely',
    'relatively',
    'apparently',
    'definitely',
    'eventually',
    'generally',
    'typically',
    'naturally',
    'basically',
    'actually',
    'obviously',
    'certainly',
    'probably',
    'possibly',
    'usually',
    'currently',
    'recently',
    'previously',
    'ultimately',
    'frequently',
  ],

  // Lifestyle & Food
  lifestyle: [
    'preparation',
    'ingredients',
    'nutritional',
    'traditional',
    'beneficial',
    'recommendation',
    'experience',
    'celebration',
    'popularity',
    'atmosphere',
    'decorative',
    'personality',
    'comfortable',
    'beautiful',
    'attractive',
    'luxurious',
    'fashionable',
    'recreational',
    'spectacular',
    'extraordinary',
  ],
}

// Flatten all categories into a single Set for quick lookup
const commonTerms = new Set(Object.values(commonTermsByCategory).flat())

module.exports = {
  commonTerms,
  commonTermsByCategory,
}
